### ISSUE TITLE
Add Tic Tac Toe [MinMax Algorithm]

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [IncrediblePro/Hacktoberfest_2022#3]
Want to add the tic tac toe game implemented with minmax algorithm and tkinter

**Comment by RathodBhavya** [comment]
Sure, you can add it, in the folder specified....!
And welcome and thanks for you contribution, and don't forget to star the repository!
@Sabyasachi-Seal

**Comment by RathodBhavya** [comment]
Create a pull request!

**Comment by Sabyasachi-Seal** [comment]
I'll get right to it
